# name: CI Pipeline

# on:
#   issue_comment:
#     branches:
#       - master
#       - develop
#   pull_request:
#     branches:
#       - master
#       - develop

# jobs:
#   sonarqube_analysis:
#     name: sonarqube_analysis
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
      
#     - name: SonarQube Scan
#       uses: sonarsource/sonarqube-scan-action@v2
#       env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         SONAR_HOST_URL:  ${{ secrets.SONAR_HOST_URL }}
        
#     - name: SonarQube Quality Gate check
#       id: sonarqube-quality-gate-check
#       uses: sonarsource/sonarqube-quality-gate-action@master
#       timeout-minutes: 5
#       env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#   codium_ai_analysis:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.sender.type != 'Bot' }}
#     permissions:
#       issues: write
#       pull-requests: write
#       contents: write
#     name: Run pr agent on every pull request, respond to user comments
#     steps:
#       - name: PR Agent action step
#         id: pragent
#         uses: Codium-ai/pr-agent@main
#         env:
#           OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           github_action.auto_review: "true"
#           github_action.auto_describe: "true"
#           github_action.auto_improve: "true"
#           pr_description.publish_labels: "true"
#           pr_update_changelog.push_changelog_changes: "true"
#           pr_code_suggestions.num_code_suggestions: 50
#           pr_code_suggestions.rank_suggestions: true
#           pr_reviewer.require_focused_review: true
#           pr_reviewer.require_score_review: true
#           pr_reviewer.require_estimate_effort_to_review: false
#           pr_reviewer.num_code_suggestions: 50
#           pr_reviewer.remove_previous_review_comment: true
#           pr_reviewer.require_all_thresholds_for_incremental_review: true 